# Generated by Django 3.1.2 on 2020-10-26 20:08

import ckeditor.fields
from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=service.models.image_upload)),
                ('img_title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
